build_platform: linux-64
c_stdlib: sysroot
c_stdlib_version: '2.17'
channel_sources: conda-forge
channel_targets: conda-forge main
cxx_compiler: gxx
cxx_compiler_version: '14'
libmamba: 2.3.3 h09abcb8_1
openssl: '3'
pybind11_abi: '4'
python: 3.12.* *_cpython
spdlog: '1.16'
target_platform: linux-64
zstd: '1.5'
